// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msljdzkqxhvnywzojpvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zbGpkemtxeGh2bnl3em9qcHZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5ODk4MjksImV4cCI6MjA2MzU2NTgyOX0.VmyBxdW0AB5K8USx58IZD7cgArJyVhuqr-Duq-e4q3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);